// Package termscan classifies bytes flowing through a terminal session so
// the session status machine reacts to what a person did, not to what the
// terminal emulator or the TUI did on its own.
//
// Two things live here:
//
//   - Bell: a streaming scanner that finds BEL (0x07) bytes in PTY output
//     while ignoring the ones that merely terminate OSC/DCS/APC/PM/SOS
//     strings. Claude Code rewrites the window title (OSC 0 … BEL) on every
//     spinner frame, so a naive byte search rings the "bell" constantly.
//   - Classify: sorts a chunk of client input into a person pressing keys,
//     a person answering a prompt, a person interrupting, or a report the
//     terminal emulator generated by itself (device attributes, cursor
//     position, mouse and focus events) which says nothing about intent.
package termscan

// Bell scans PTY output for bells outside control strings. The zero value
// is ready to use. It is not safe for concurrent use.
type Bell struct {
	state bellState
}

type bellState uint8

const (
	ground bellState = iota
	esc              // saw ESC, deciding what follows
	csi              // inside CSI, ends at a final byte 0x40..0x7e
	str              // inside OSC/DCS/APC/PM/SOS, ends at BEL or ESC \
	strEsc           // inside a string and saw ESC (ST is ESC \)
)

// Feed consumes a chunk and reports how many real bells it contained.
func (b *Bell) Feed(p []byte) int {
	bells := 0
	for _, c := range p {
		switch b.state {
		case ground:
			switch c {
			case 0x07:
				bells++
			case 0x1b:
				b.state = esc
			}
		case esc:
			switch c {
			case '[':
				b.state = csi
			case ']', 'P', '_', '^', 'X':
				b.state = str
			case 0x1b:
				// stay in esc
			case 0x07:
				bells++
				b.state = ground
			default:
				b.state = ground
			}
		case csi:
			if c >= 0x40 && c <= 0x7e {
				b.state = ground
			} else if c == 0x1b {
				b.state = esc
			}
		case str:
			switch c {
			case 0x07:
				b.state = ground
			case 0x1b:
				b.state = strEsc
			}
		case strEsc:
			switch c {
			case '\\':
				b.state = ground
			case 0x1b:
				// stay
			case 0x07:
				b.state = ground
			default:
				b.state = str
			}
		}
	}
	return bells
}

// InputKind is what a chunk of client input most plausibly is.
type InputKind int

const (
	// Report is generated by the terminal emulator, not typed: replies to
	// device queries, cursor position and size reports, focus and mouse
	// events. It carries no signal about the person.
	Report InputKind = iota
	// Keys is ordinary typing or navigation that does not itself commit
	// anything: printable text, arrows, backspace, pasted text.
	Keys
	// Answer is a keystroke that submits or picks: Enter, y/Y, or a digit.
	Answer
	// Interrupt is a bare Escape or Ctrl-C.
	Interrupt
)

// Classify sorts an input chunk. A chunk is a Report only if every token in
// it is one; an Interrupt only if it is exactly one bare Escape or Ctrl-C;
// an Answer if any token is an answering key; otherwise Keys.
func Classify(p []byte) InputKind {
	if len(p) == 0 {
		return Report
	}
	if len(p) == 1 && (p[0] == 0x1b || p[0] == 0x03) {
		return Interrupt
	}
	kind := Report
	for i := 0; i < len(p); {
		n, k := token(p[i:])
		if k > kind {
			kind = k
		}
		i += n
	}
	return kind
}

// token classifies the first sequence in p and returns its length.
func token(p []byte) (int, InputKind) {
	c := p[0]
	if c != 0x1b {
		switch {
		case c == '\r' || c == '\n' || c == 'y' || c == 'Y' || (c >= '1' && c <= '9'):
			return 1, Answer
		case c == 0x03:
			return 1, Interrupt
		}
		return 1, Keys
	}
	if len(p) == 1 {
		return 1, Interrupt // bare Escape at the end of a chunk
	}
	switch p[1] {
	case '[':
		return csiToken(p)
	case 'P':
		// DCS … ST: the tertiary device attributes reply and similar.
		for i := 2; i+1 < len(p); i++ {
			if p[i] == 0x1b && p[i+1] == '\\' {
				return i + 2, Report
			}
		}
		return len(p), Report
	case 'O':
		// SS3 keys (arrows in application mode, F1-F4).
		if len(p) >= 3 {
			return 3, Keys
		}
		return len(p), Keys
	}
	// Alt+key: ESC followed by one character.
	return 2, Keys
}

func csiToken(p []byte) (int, InputKind) {
	// p[0]=ESC p[1]='['. Find the final byte.
	end := -1
	for i := 2; i < len(p); i++ {
		if p[i] >= 0x40 && p[i] <= 0x7e {
			end = i
			break
		}
	}
	if end < 0 {
		return len(p), Keys
	}
	final := p[end]
	params := p[2:end]
	n := end + 1
	switch {
	case final == 'M' && len(params) == 0:
		// X10 mouse: CSI M followed by three bytes.
		if len(p) >= n+3 {
			return n + 3, Report
		}
		return len(p), Report
	case (final == 'M' || final == 'm') && len(params) > 0 && params[0] == '<':
		return n, Report // SGR mouse
	case final == 'I' || final == 'O':
		if len(params) == 0 {
			return n, Report // focus in / out
		}
	case final == 'c' || final == 'n' || final == 'R':
		return n, Report // DA1/DA2, DSR, CPR
	case final == 't':
		if len(params) > 0 && params[0] == '8' {
			return n, Report // size report
		}
	case final == '~':
		// Bracketed paste: everything up to the closing CSI 201 ~ is Keys.
		if string(params) == "200" {
			if j := indexOf(p[n:], []byte("\x1b[201~")); j >= 0 {
				return n + j + 6, Keys
			}
			return len(p), Keys
		}
	}
	return n, Keys
}

func indexOf(p, sub []byte) int {
	for i := 0; i+len(sub) <= len(p); i++ {
		match := true
		for j := range sub {
			if p[i+j] != sub[j] {
				match = false
				break
			}
		}
		if match {
			return i
		}
	}
	return -1
}
